apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_USER: cm9vdA==  # base64 encoded value of 'root'
  MYSQL_PASSWORD: bXlzcWwxMjM=  # base64 encoded value of 'mysql123'
  MYSQL_DATABASE: c2Nob29s  # base64 encoded value of 'school'

